### ISSUE TITLE
Seite nicht aktualisiert nach AJAX /buy_item  POST Aufruf

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#1]
Wenn man ein Item kauft, wird die Seite nicht automatisch refreshed. Wenn man die Seite mit F5 refreshed, wird das nun inaktive und gekaufte Item nicht mehr angezeigt.

**Comment by rothfahl** [comment]
redirect / eingefügt, das scheint zu helfen...

**Comment by MichaelKohler** [comment]
Oha, hab gedacht, dass ich das auch versucht hatte. Funktioniert super, danke!
