### ISSUE TITLE
Generate activities

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#102]
Whenever a user/organization
- Comments
- Follows someone
- activates an item

an activity should be added to its activity list (in the Agent class)

This is the activities that "following" users see.

All of these activities are also added to the organization we are currently working for (with creator = current login) if there is any.
When working for an organization, we additionally track (in the activity list at the org):
- Buying items
- Adding items

**Comment by Masterxilo** [comment]
Implement at controller level. I added TODO's.

**Comment by rothfahl** [comment]
I belief we should refactor this an move the creation of Activity-Objects to the model layer. Its business logic, isn't it? And it's hardly testable when implemented in the controllers.

**Comment by Masterxilo** [comment]
Right, but it's much harder to do because the currently logged in user is not reflected in the model, so how do we generate the organization's activities (orgactivities)? Its quite easy to do on the controller level.

**Comment by rothfahl** [comment]
Hmm, why do we need the current_user in the model? I'd say, we introduce a class AchtivityLog that collects all activities from all agents. Activities get created from add_comment(), buy_item() et. al. and activities store their user. ActivityLog offers some methods to query activities (by users, by types, both). To display a list, we simple query the ActivityLog for activities that where issued by the users the current_agent follows and the activity types we want to display. For the activities of an organisation we query for activities of the orgs users and the additional types.

**Comment by Masterxilo** [comment]
> "For the activities of an organisation we query for activities of the orgs users and the additional types.

That's not how it works. The activities of an organization are not the activities of the orgs users. 

With the arrays I prepared, it would work in the following way: There are two lists for the "activities of an organization":
The "activities" list in Agent 
and the "orgactivities" list.

The activities list will contain only activities that will be visible to users following the organization. These activities are commenting, activating items and following someone (but an org can't do that anyways). All of these activities have creator = the organization.

orgactivities on the other hand stores the organization-internal activities, that is the activities of its members _while they are working for the org_. These activities store creator = current_user (not current_agent). 

All of this activity monitoring would be very hard to add on the model level (buy_item would have to generate an activity for the agent that is buying the item AND an orgactivity if this is an organization - for which it would additionally have to know the user making that buying decision).

**Comment by Masterxilo** [comment]
I really recommend generating the activities on the controller level for now (because of the current_user != current_agent) problematic.

However, I see that having a global activity list might simplify things. 
- Have activities store an "agent" and an optional "executor".
- When any action for which an activity type exists is executed, add an activity with agent = current_agent, executor = current_user.
- When displaying the activities of the agents a user follows, simply filter that list for all activities with agent = someone I'm following and activity-type = comment, activate, follow. (Note that the actual executor shall not be displayed to users just following the organization. )
- When displaying the organization-internal activities, simply filter the activities list for those with agent = @org and display them prefixed with the executor.
