### ISSUE TITLE
adapt model of item

### ISSUE THREAD

**Issue by Lafunamor** [ese-unibe-ch/ese2012-team3#108]

**Comment by pas** [comment]
At the moment there exists one more class variable called "auction" which stores the auction object.

There is as well an method called #auction? to check if an item is currently on auction.

**Comment by pas** [comment]
Finished it. We could do better by distinguish between 
1) active, which means is in selling mode (either auction or fixed price)
2) fixed, which means in selling mode fixed
3) auction, which means in selling mode auction
But I think this is not so important
