### ISSUE TITLE
make a bid 

### ISSUE THREAD

**Issue by Lafunamor** [ese-unibe-ch/ese2012-team3#111]
the bid contains the maximal value

max value has to be price + increment \* x

two bidders cannot have the same maximal price

**Comment by pas** [comment]
TODO:

1) Create 'post 'item/:id/bid' in controller marketplace
then in  that entry do
2) Get item by Item.by_id(params[:id].to_i)
3) Set bid: item.auction.offer(User.by_id(session[:user_id], params[:bid].to_i))

Make some error checking for example
- Check that it is not bid on a closed auction (auction.closed?)
- etc.
