### ISSUE TITLE
auction view

### ISSUE THREAD

**Issue by Lafunamor** [ese-unibe-ch/ese2012-team3#112]
buyers can see: item, minimal price, increment, current winner, current selling price

**Comment by pas** [comment]
If an auction is set a possible bidder can click on the button "Auction" and is redirected to /item/:id/auction. This page is not yet implemented in controller and view.

**Comment by pas** [comment]
TODO:

1) Show more information in view 'auction.erb'
- current winner
- increment

You can get those information from auction: auction.increment and auction.winner
