### ISSUE TITLE
winnerchange mail notification

### ISSUE THREAD

**Issue by Lafunamor** [ese-unibe-ch/ese2012-team3#113]

**Comment by pas** [comment]
The best way is possibly just to use our code because there is no predefined code.

**Comment by pas** [comment]
TODO:
1) Import our simple_email_client.rb to this repo
2) Create new gmail account
3) make an email notification every time the user changes. For that you probably fit this in in Auction#determine_winner under "unless self.winner == current_winner". See our project and my email about this topic to find out how the SimpleEmailClient works.
