### ISSUE TITLE
Create Auction view

### ISSUE THREAD

**Issue by pas** [ese-unibe-ch/ese2012-team3#121]
TODO:

1)  Select a date and time instead of a empty field

**Comment by pas** [comment]
Some ideas:

http://www.mattkruse.com/javascript/calendarpopup/
http://www.javascriptkit.com/script/script2/tengcalendar.shtml

**Comment by pas** [comment]
They already use jQuery so this could be interesting:

http://docs.jquery.com/UI/API/1.8/Datepicker

**Comment by DKPillo** [comment]
done
