### ISSUE TITLE
wo & wie das review machen ?

### ISSUE THREAD

**Issue by lyriael** [ese-unibe-ch/ese2012-team3#126]
Ich bin jetzt grad etwas verwirrt: Schreiben wir das review direkt in den Code (also im review branch) oder als ein externes file?

oder am besten beides? Während dem code lesen ist es sehr praktisch direkt rein zuschreiben.

**Comment by BT272** [comment]
Also ich fände es nicht schlecht in einem externen File, da die Review ja eigentlich zusammenfassend sein sollte, d.h. bei uns jetzt zum Beispiel ein Review File zu den Controllern usw. Wenn wir jedoch direkt im Code arbeiten, haben wir für jede einzelne File eine Art Review, was zum Teil auch zu Wiederholungen führen kann, da etwas gleich in mehreren Files auftritt. Was denkt ihr?

**Comment by pas** [comment]
Ich denke es geht schneller, wenn wir es in den Code schreiben (als kurzes Statement mit Tag "# cr:" und anschliessend in ein externes File, so wie es jetzt ja eigentlich bei Maudlin war. Das ist auch hilfreicher für die anderen. Sie können sich dann einfach den Code anschauen, wo genau wir gemeint haben und wir müssen uns in der Zusammenfassung keine Gedanken machen über Verweise zum Code, sondern können einfach reinen Text schreiben.

**Comment by pas** [comment]
Für die abschliessend Zusammenfassung ist es dann einfach die Tags einfach mittels RubyMine anzuzeigen:

File -> Settings -> TODO

1) Pattern einrichten: "\bcr\b.*" 
2) Filter einrichten
3) "Apply" 
4) Hauptfenster unten links "6: TODO" auswählen
5) Filter einstellen (Trichtersymbol auf der linken Seite).
6) Et voilà

**Comment by lyriael** [comment]
arg... irgendwie ist github grad komisch drauf. Ich hab vorhin noch was dazu geschrieben, dann wurde es 3 mal gepostet, also habe ich es 2 mal davon gelöscht und jetzt steht es gar nicht mehr da... -.-

danke @pas (und ja ich weiss, jedes mal, wenn ich @pas mache bekommst du noch eine extra mail _g_)
