### ISSUE TITLE
Item search mechanics (search implementation)

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#134]
I suggest the description content should also be searched, maybe even the comments. The results should be sorted by relevance with items that match the search by title the most relevant, then by description and then comments.

Maybe we can use a gem e.g. http://florianhanke.com/picky/ or https://www.ruby-toolbox.com/projects/ferret
### Description

Story 26: As an authenticated user, I can search with free text for items that interest me.

Acceptance criteria: the display must be compact to list many items, and a quick view expand an item "in place" without redirecting to another page.

**Comment by lvoegtlin** [comment]
picky requires ruby 1.9

**Comment by MichaelKohler** [comment]
AFAIK there are gems we use that don't really work with 1.9.3.. Or did anybody get it working?

**Comment by MichaelKohler** [comment]
with c4ca2c442b14a8dfdb591dad4e7fbf2e6d8fbe56 I introduced the following:
- search result display with the normal _item_list
- no ordering of the display!
- search in title and about of the item
- acceptance criteria not yet met: does not expand in place

**Comment by MichaelKohler** [comment]
Who has an idea how we could implement the "expand in place" thing?
