### ISSUE TITLE
Ensure table column width are consistent no matter the content

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#141]
Right now the layout can change quite a bit when filters are applied or items with certain attributes are visible

**Comment by MichaelKohler** [comment]
Where exactly? Since you talk about filters, it gotta be "Activites", but I don't see any problem there.

**Comment by MichaelKohler** [comment]
Also, if we're gonna do this, we should only use % since our layout is really flexible and shoudn't contain any width in em, px, ...

**Comment by Masterxilo** [comment]
It's also noticeable in the items, e.g. it's different when there is an item by you or not or when there is an item on auction or not.

**Comment by MichaelKohler** [comment]
This problem is also present on user lists.

**Comment by MichaelKohler** [comment]
Since we have a pretty flexible layout now (thinking about the item buttons), this is gonna be hard. But if somebody wants to give a try, feel free ;)

**Comment by Masterxilo** [comment]
I guess we can drop this.
