### ISSUE TITLE
Buy offers

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#149]
As a buyer, I can enter a buy offer. 
The item gets created, as soon as somebody sells me this item. The credits for this offer, get blocked for the time the offer is valid.

Suggested Implementation:
- Creating an item buy offer works just like creating a normal item.
- "Buy offer" is merely a special item state.
- When you create a buy offer, you lose the credits you offer.
- As soon as anybody sells you this item (by simply pressing on sell instead of buy), he gets the money and the item turns into a normal inactive item you own.

**Comment by MichaelKohler** [comment]
weird push order, but it's done.. (accidentally pushed to stable and then merged it to master)
