### ISSUE TITLE
Language support for English, German and French - For activity messages

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#150]
I suggest instead of storing string creating an object that holds a sequence of strings and language identifiers which can then convert itself to a string given a language.

E.g.
"John commented on pizza" would then be stored as

"John" (type: literal String), "COMMENTED_ON" (type: lang identifier), "pizza"

and every lang identifier would be replaced with @LANG[...] at display time.

**Comment by MichaelKohler** [comment]
we should use https://github.com/ai/r18n .. then it's quite easy I think
