### ISSUE TITLE
Create system admin page - admin can delete all kinds of entities - login

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#158]
Story 35: As a admin I can log myself in, in an admin interface and delete all entities (item, offer, auction, user, organization).

---

The admin page should be accessible under a separate URL and password protected (no users required, can be hardcoded).

It should allow the admin to delete all entities we have. I guess would be fine if the admin page is not localised and simply throws exceptions on error instead of nice messages.

**Comment by Masterxilo** [comment]
- items
- users
- auctions
- organizations

**Comment by Masterxilo** [comment]
I'm splitting these up a little

**Comment by MichaelKohler** [comment]
I think basic authentication is enough, therefore I'm closing this issue.
