### ISSUE TITLE
Add UI tests

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#16]
We should add some basic UI tests (probably Selenium)  so we don't fuck up our design later.

**Comment by MichaelKohler** [comment]
not necessarily for sprint 1 -> removing milestone

**Comment by Masterxilo** [comment]
Don't you think this is still overkill for sprint 2?

**Comment by MichaelKohler** [comment]
let's stick with Sprint 2 and see if there is time.

**Comment by MichaelKohler** [comment]
Todo: enable settings tests

**Comment by MichaelKohler** [comment]
Todo: add organization tests

**Comment by MichaelKohler** [comment]
Todo: test comment function
