### ISSUE TITLE
Fix search (undefined method include?

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#168]
I currently get

NoMethodError at /item/search
undefined method `include?' for #LocalizedLiteral:0x89e9f08

no matter what i try to search.

**Comment by bESE** [comment]
Hello,
Me and Lars are currently looking for the error... did it work after you (paul) added the localizedliteral stuff? (so we know where to search)

**Comment by Masterxilo** [comment]
When I added the localized stuff it was still the old layout and I think it worked. I didn't work after I pushed and merged and the new layout was there.
