### ISSUE TITLE
Admin control panel main page - display key numbers/amounts - users, items,...

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#174]
Show some values concerning the amount of things in the system, e.g. amount of users, items etc. Be creative.

Put this stuff in the admin control panel index page.

**Comment by fmatter** [comment]
sry michael, has scho am friti aabe gmacht gha u itz haut widr :/

**Comment by MichaelKohler** [comment]
no worries, it works -> close
