### ISSUE TITLE
Admin can change localization keys' values - basic page

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#178]
Story 37: "As a admin I can change the translation values either with an awesome web gui or via import/export functionality."

The customer suggests picking one of the following implementations:
- Let the admin download, edit and reupload a csv file with the language keys -- this requires a lot of input validation
- Use a web GUI. Please allow filtering the list.

---

I'm in favor of the second alternative.
Of course it would be nice if the changes were reflected in the languages files and stored there permanantly but we don't have to do that (we don't do that with any userdata either).

**Comment by MichaelKohler** [comment]
I prefer the second solution since this is way more userfriendly for non-technical admins.

**Comment by MichaelKohler** [comment]
also, we should split this up in more issues once we have a decision

**Comment by fmatter** [comment]
i'm also in favor of the GUI option

**Comment by Masterxilo** [comment]
I guess that settles it then (3/6). I'll let the customer know.
