### ISSUE TITLE
Admin can change localization keys' values - key filtering by category

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#180]
key_categories.txt lists the categories

**Comment by Masterxilo** [comment]
I suggest doing this via javascript - just hide the categories that are not selected.

**Comment by MichaelKohler** [comment]
We could also "hide" all content from every category and then do something similar to the show content arrow on the past winners list. What do you think?

**Comment by Masterxilo** [comment]
Sure.

**Comment by MichaelKohler** [comment]
closed by 5d70271 .. unfortunately I couldn't do it with the "hidden" class in bootstrap and "addClass" and "removeClass" in JQuery, so I used Vanilla JS.
