### ISSUE TITLE
buying from search page doesn't work

### ISSUE THREAD

**Issue by fmatter** [ese-unibe-ch/ese2012-team3#191]
i think it's because we're redirecting back to a post page?

**Comment by MichaelKohler** [comment]
Actually we are redirecting back to /search (since we're coming from /search) and this means that it is a GET request and no GET request handler for /search is defined. What should we do here? Should we redirect to '/' when trying to access '/search' with a GET request?

**Comment by fmatter** [comment]
yeah, that's what i meant xD. there's only a post handler for search. and yes, we could redirect to the marketplace and show the normal "you bought xxx" message. it's just not very elegant, since the user will have to make the search again in case he's looking for several specific items...

**Comment by fmatter** [comment]
doing a redirection to "/" for now.

**Comment by MichaelKohler** [comment]
We could save the last search as a value and redo the search after buying the item, but every implementation I can think of is pretty ugly, so we better do nothing more here. Agreed?

**Comment by fmatter** [comment]
or we could remake the search to a GET request, although that's also pretty ugly... let's leave it.

**Comment by MichaelKohler** [comment]
Wait, why not GET? We're not modifying data in the search so this could be GET, couldn't it?

**Comment by Masterxilo** [comment]
Yeah then we could also have links to specific searches if you pass the parameters via url as it is usually done with searches (e.g. google).
