### ISSUE TITLE
fix selenium tests - all tests in selenium.rb seem to fail

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#193]
But this is actually pretty cool!? So that selenium opens the website in firefox and play around with the interface?

**Comment by MichaelKohler** [comment]
Yes, I had that in mind and will do it next week when we clean up :)

And yes, Selenium is awesome!

**Comment by MichaelKohler** [comment]
fixed all the tests (there are still 2 tests which are not run at the moment, but all tests which are run pass!)
