### ISSUE TITLE
23 not fully implemented: "As buyer or seller, I can watch a user, organization *or item* so that I can easily track activity related to them." 

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#213]
We got the points, but we never implemented "watching" an item.

I guess we have to check with the customer to see if this is ok. We do have wishlists, but that's not the same.

**Comment by MichaelKohler** [comment]
What's the status here?

**Comment by Masterxilo** [comment]
Need to write mail I guess.
