### ISSUE TITLE
switch to org settings when on settings page when switching to representing org

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#217]
Currently, if you are editing your users settings then change to represent an org you are still on your user settings page but the nave show that you are on org settings. 

Maybe we can redirect to the orgs settings page if @current_user. last visited page is /settings

But this is really minor.

**Comment by Masterxilo** [comment]
Edit: Same goes for switching back to representing an user when on org settings page.

**Comment by Masterxilo** [comment]
If you are willing to, we could just make the url /settings show the right page depending on whether current_agen is an org or user, this would fix both directions

**Comment by fmatter** [comment]
i think that makes sense, since there should only one settings page be available to the user at any given moment - either his own or that of the org he's working for.
