### ISSUE TITLE
item creation: prevent adding same language again

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#218]
From Joel:

"Also the bug from last week seems to be fixed (localization). Only confusing thing:
The system doesn't prevent me from entering the same language twice. It then seems to take only one of them, so it's more of an usuability issue as I can not get the system to an inconsistent state. "

**Comment by Masterxilo** [comment]
This should be possible with js - just delete the options selected in upper boxes from all lower ones. The first one will always allow all.

**Comment by rothfahl** [comment]
Not as simple as I thought. The user can change already selected languages at any time. So removing options in lower select boxes won't do. 
E.g. english description is given. User adds another fieldset, options are de, fr, jp. User changes language in first form from en to de. -> Two de forms

My second thought: Removing the selected lang at change event from all other select boxes won't do neither. Same problem, user can change language of upper boxes.

Guess the way to do it would be to save name/description for each language separately in its own form. New forms could be loaded by ajax calls after the user has loaded.

Anyone a simple idea?

**Comment by Masterxilo** [comment]
Why not reset everything to all 4 languages on a change, then 

for each selection box: delete my selection in all lower boxes

?
