### ISSUE TITLE
ese password

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#219]
From the 2nd cycle delivery notes:

"Provide demo data and accounts to test the application. There must be a user/pwd ese/ese that can be used to test the application."

how could we do that?

**Comment by bESE** [comment]
password strength is only checked in User.init ->
add in app.rb after (line98)
ese = User.init(:name => "ese", :credit => 1000, :password => DEFAULT_PASSWORD)
ese.password = "ese"
