### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by bESE** [ese-unibe-ch/ese2012-team3#220]
Hi,
We have to present it tomorrow, right? is there any lists what they want to see, or did any1 planned something yet?

**Comment by fmatter** [comment]
I didn't see any list; they just listed the criteria [here](https://github.com/ese-unibe-ch/ese2012-wiki/wiki/Delivery-2nd-Cycle). What can we show? I think the stuff worth presenting is:
- Organizations
- Offers
- Languages
- Items in different languages
- Admin panel
- Following
- Wishlist
- Comments
- Search
- ...anything else that might be interesting to see?

**Comment by MichaelKohler** [comment]
Unfortunately I won't be able to join you for the presentation. You'll do awesome since your project is the best one around :+1:

**Comment by MichaelKohler** [comment]
*our project :)

**Comment by MichaelKohler** [comment]
http://ese.michaelkohler.info has the latest HEAD and seems to work :) Have fun with the presentation

**Comment by fmatter** [comment]
actually, http://ese.michaelkohler.info seems to have a problem with switching languages, whereas http://michaelkohler.info:4567/ seems to work fine.
