### ISSUE TITLE
create item detail page

### ISSUE THREAD

**Issue by fmatter** [ese-unibe-ch/ese2012-team3#23]
1 image, name, description, price, seller, OWNER:(activate/inactivate button, edit button - like on the user profile view), BUYER:(buy button)

**Comment by MichaelKohler** [comment]
nice idea! we should link to this item detail view from everywhere where the item name is (except forms input fields ;))

**Comment by fmatter** [comment]
the page exists, the issue is still open because of the missing comment form and markdown implementation.

**Comment by MichaelKohler** [comment]
i think this is enough for this (for the other things there are separate issues)
