### ISSUE TITLE
Username can contain characters forbidden in URLs or with special meaning

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#26]
e.g " ", "hi/there" etc. which will cause the profile/ page link to fail. We should add a namecheck class that will be used for items as well which limits the range of characters etc.

**Comment by MichaelKohler** [comment]
I think a username should be only [a-zA-z0-9_-]. Do you agree?

Items should have the same characters allowed, but extendend by \s.

**Comment by Masterxilo** [comment]
Not sure about space, people might want to enter their real name. Many systems allow this. Just no trailing/leading space.

**Comment by MichaelKohler** [comment]
Well, I agree, trailing and leading spaces can be stripped when
processing, we shouldn't display an error just for that.

**Comment by rothfahl** [comment]
Or maybe we just stop using the name as ressource-id and change our routes to /profile/:id?

**Comment by MichaelKohler** [comment]
Oh,  we should definitely use the id there.

**Comment by MichaelKohler** [comment]
Oh,  we should definitely use the id there.

**Comment by Masterxilo** [comment]
This goes together with issues #48 and #46...

**Comment by rothfahl** [comment]
Changed routes to /profile/:id/...
Use session[:user_id] to load current user
