### ISSUE TITLE
Registration and password changing errors should be displayed inline

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#27]
Just as on the edit item page (enter a negative price). I really like that.

**Comment by rothfahl** [comment]
Ich hab das gemacht, indem ich einen hash @errors im controller eingeführt habe und in der View schaue, ob da was drin steht. Vielleicht hat jemand eine bessere, generischere Idee für Form-Validierung. Vielleicht gibts auch ein nettes gem. ...wär doch schön, wenn man sowas in der View nicht von Hand machen müsste.

**Comment by Masterxilo** [comment]
Problem: All previous input is erased, that doesn't happen with the error page and then going back...

**Comment by Masterxilo** [comment]
Worked some on this... I don't think this needs to be in sprint 2.

**Comment by MichaelKohler** [comment]
Fixed by checkin a0ba0fcac7e571683951e3bfb485e502bb56a1a5
