### ISSUE TITLE
exceptions werfen in user.buy_item

### ISSUE THREAD

**Issue by rothfahl** [ese-unibe-ch/ese2012-team3#3]
user.buy_item sollte exceptions werfen, wenn was unerlaubtes versucht wird (Preis zu hoch, inaktives item, etc). Dafür kann dann auf user.buy_item? verzichtet werden.
Exceptions können im Controller gefangen werden und die an die error-view weitergegeben werden.

**Comment by MichaelKohler** [comment]
fixed by 6c144dd
