### ISSUE TITLE
Create organization add form

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#39]
- Link to the form
- Don't forget: "Acceptance criteria: the user is the admin of the newly created organization"

**Comment by Masterxilo** [comment]
#42, #41, #40, #44, #54 hängen nicht direkt davon ab (man kann ja im Code eine Organisation erstellen zum testen), also ist das nicht zwingend more ASAP nötig als die anderen.

**Comment by MichaelKohler** [comment]
mache ich heute Abend noch ;)

**Comment by MichaelKohler** [comment]
implemented by commit 31f8f98a974a54c1bf4e80cb31b0f6766b1a2fee
