### ISSUE TITLE
User and organization icon

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#41]
in the marketplace at the owner column we should have "user" and "organization" icons in front of the owner name

**Comment by MichaelKohler** [comment]
If we are lucky we find a good icon in the bootstrap icons (similar to the sidebar)

**Comment by fmatter** [comment]
i found a user icon but no group icon. the icons are provided by http://glyphicons.com/, there's a free set available that provides 400 icons in the same style, is it possible to use these within bootstrap?

**Comment by MichaelKohler** [comment]
It's not that easy.  I think we have to do it with "normal" HTML and CSS.

**Comment by fmatter** [comment]
using an asterisk placeholder for now.
