### ISSUE TITLE
always use User.id instead of name

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#46]
-> session[id] instead of session[name]
-> everywhere else

**Comment by rothfahl** [comment]
oha, flöru, das hab ich dir wegenommen. Hab mit #26 auch gleich session[:user_id] eingeführt und session[:name] entfernt. Aber eine review wäre angebracht :-)

**Comment by MichaelKohler** [comment]
review+, functional test sieht auch gut aus :) schön gemerged! somit ist das nun erledigt -> Close
