### ISSUE TITLE
Have global $ID_COUNTER instead of one per class

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#51]
This is important for image IDs for items, users and organizations (must be globally unique). Unless we don't want to store all images in one folder (which the current design - with a userimages folder) suggests...

And items will have multiple images anyways so we'll have to think of something else for these - unless of course, we also give out IDs for item IMAGES. Why not, I guess we have billions of them available...

**Comment by MichaelKohler** [comment]
We should give pics an individual ID and just use a global ID for organizations and users.  I would like to separate items from agents as much as possible.

**Comment by MichaelKohler** [comment]
When we introduce multiple images per item, we should have an unique ID for the images and store it like:

{UNIQUE_ITEM_ID}_{UNIQUE_IMAGE_ID}

We won't conflict with the user images anyway.
