### ISSUE TITLE
As a user, I can delete my account

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#6]

**Comment by MichaelKohler** [comment]
Link auf User-Profile

**Comment by rothfahl** [comment]
I'll do that, if nobody wants to claim it.
What shall happen with a users items when he deletes himself? Delete them too? I guess so?! Or do we need to ask uor customer first?

**Comment by MichaelKohler** [comment]
I think we should delete the items too. But asking the customer wouldn't
hurt..
