### ISSUE TITLE
catch all exceptions with halt in error.rb

### ISSUE THREAD

**Issue by MichaelKohler** [ese-unibe-ch/ese2012-team3#70]
... if not catched elsewhere

**Comment by MichaelKohler** [comment]
fixed by 7b24cee499bd2af3ea098f174c9c774b78f1287d

**Comment by MichaelKohler** [comment]
not really fixed somehow, when running with `RACK_ENV=test ruby app/app.rb` I get a white 500 page..

http://localhost:4567/settings -> /delete_confirmation?_method=delete
[2012-10-19 21:04:52] ERROR RuntimeError: cannot remove admin, set a new admin first!
    /media/Data/Dropbox/Universitaet/3. Semester/ESE/ese2012-team3/app/models/market/organization.rb:64:in `remove_member'
    /media/Data/Dropbox/Universitaet/3. Semester/ESE/ese2012-team3/app/models/market/user.rb:78:in`delete'
    /media/Data/Dropbox/Universitaet/3. Semester/ESE/ese2012-team3/app/models/market/user.rb:77:in `each'
    /media/Data/Dropbox/Universitaet/3. Semester/ESE/ese2012-team3/app/models/market/user.rb:77:in`delete'
    /media/Data/Dropbox/Universitaet/3. Semester/ESE/ese2012-team3/app/controllers/user.rb:24:in `DELETE /profile/:id'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `compile!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`[]'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in`route_eval'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in`process_route'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in`process_route'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in`each'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in`dispatch!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /var/lib/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in`call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in`synchronize'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in`service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
    /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:82:in`start'
    /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:13:in `run'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in`run!'
    /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
    app/app.rb:51
localhost - - [19/Oct/2012:21:04:52 CEST] "POST /profile/4 HTTP/1.1" 500 323
http://localhost:4567/delete_confirmation?_method=delete -> /profile/4

**Comment by rothfahl** [comment]
hmm, right. It does work in production though
At least when i run 
ruby app.rb -e production

**Comment by MichaelKohler** [comment]
is production enough? IMHO it is..

**Comment by rothfahl** [comment]
Yep, i guess production is enough. 
Aber was jetzt? Heisst das, bei dir springt auch unter production der error-handler nicht an?

**Comment by MichaelKohler** [comment]
Weiss gerade nicht, was im Moment eine Exception wirft (der Delete Button is ja nun deaktiviert).. Heeelp? :)

**Comment by rothfahl** [comment]
z.B. http://localhost:4567/item/666

**Comment by MichaelKohler** [comment]
works when run in production mode -> Close
(I will start it on the stage server in production mode)
