### ISSUE TITLE
NON CODE: Present two design problems/decisions we faced, wednesday

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#86]
See https://github.com/ese-unibe-ch/ese2012-wiki/wiki/design-decisions-presentation 
for requirements.

Will be a presentation of 5 minutes again.

I'll present the problem with linking the user and the organizations he belongs to.

We need one other problem.

**Comment by Masterxilo** [comment]
Here's my part: https://www.dropbox.com/sh/nou6l9x26vwnca2/aJLjxNltQV

**Comment by rothfahl** [comment]
looks great!

**Comment by Masterxilo** [comment]
Well, does anybody have any Ideas for another decision? If not, I'll just do that presentation but it be very nice to have someone else do an introduction, meaning quickly (30 secs) saying what we are going to present (that is, quickly summarize "hints for content" of https://github.com/ese-unibe-ch/ese2012-wiki/wiki/design-decisions-presentation ).

Who would be ok with doing that?

**Comment by MichaelKohler** [comment]
Thanks, well done!
