### ISSUE TITLE
create quote/reply function

### ISSUE THREAD

**Issue by fmatter** [ese-unibe-ch/ese2012-team3#92]
once issue #73 is finished, add quoting / answering functionality to the comments section. a form + button already exists, but i'm not sure that's the right solution.

**Comment by MichaelKohler** [comment]
it is, I'll take this and add it onclick to the form to add a comment. any objections?

**Comment by MichaelKohler** [comment]
One problem:

we should use a > in markdown to indicate a blockquote.. our lovely XSS filter escapes it and redcarpet doesn't recognize it after that.. Any idea?

**Comment by fmatter** [comment]
i guess simply leaving out the xss filter is not the way to go, huh? :P
